name = "tocketicket-api-messaging-worker"
main = "src/index.ts"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
WHATSAPP_PHONE_NUMBER_ID = "815331504680848"
WHATSAPP_API_BASE_URL = "https://graph.facebook.com"
WHATSAPP_API_VERSION = "v25.0"
MONGO_DB = "ticketera"

[observability.logs]
enabled = true
invocation_logs = true